/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedTokenDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decrypt"
      | "distribute"
      | "distributeBatch"
      | "emergencyWithdraw"
      | "getDecryptionKeyHash"
      | "isUsed"
      | "owner"
      | "renounceOwnership"
      | "setDecryptionKey"
      | "setToken"
      | "token"
      | "transferOwnership"
      | "usedHashes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionKeyUpdated"
      | "OwnershipTransferred"
      | "TokenUpdated"
      | "TokensDistributed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "decrypt", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeBatch",
    values: [BytesLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptionKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isUsed", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDecryptionKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedHashes",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "decrypt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptionKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isUsed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDecryptionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedHashes", data: BytesLike): Result;
}

export namespace DecryptionKeyUpdatedEvent {
  export type InputTuple = [oldKey: BytesLike, newKey: BytesLike];
  export type OutputTuple = [oldKey: string, newKey: string];
  export interface OutputObject {
    oldKey: string;
    newKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensDistributedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    encryptedValue: BytesLike,
    distributor: AddressLike
  ];
  export type OutputTuple = [
    recipient: string,
    amount: bigint,
    encryptedValue: string,
    distributor: string
  ];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    encryptedValue: string;
    distributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedTokenDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedTokenDistributor;
  waitForDeployment(): Promise<this>;

  interface: EncryptedTokenDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decrypt: TypedContractMethod<[encryptedValue: BytesLike], [bigint], "view">;

  distribute: TypedContractMethod<
    [encryptedValue: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  distributeBatch: TypedContractMethod<
    [encryptedValues: BytesLike[], recipients: AddressLike[]],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  getDecryptionKeyHash: TypedContractMethod<[], [string], "view">;

  isUsed: TypedContractMethod<[encryptedValue: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDecryptionKey: TypedContractMethod<
    [_newKey: BytesLike],
    [void],
    "nonpayable"
  >;

  setToken: TypedContractMethod<[_newToken: AddressLike], [void], "nonpayable">;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decrypt"
  ): TypedContractMethod<[encryptedValue: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distribute"
  ): TypedContractMethod<
    [encryptedValue: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeBatch"
  ): TypedContractMethod<
    [encryptedValues: BytesLike[], recipients: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDecryptionKeyHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isUsed"
  ): TypedContractMethod<[encryptedValue: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDecryptionKey"
  ): TypedContractMethod<[_newKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setToken"
  ): TypedContractMethod<[_newToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "DecryptionKeyUpdated"
  ): TypedContractEvent<
    DecryptionKeyUpdatedEvent.InputTuple,
    DecryptionKeyUpdatedEvent.OutputTuple,
    DecryptionKeyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenUpdated"
  ): TypedContractEvent<
    TokenUpdatedEvent.InputTuple,
    TokenUpdatedEvent.OutputTuple,
    TokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensDistributed"
  ): TypedContractEvent<
    TokensDistributedEvent.InputTuple,
    TokensDistributedEvent.OutputTuple,
    TokensDistributedEvent.OutputObject
  >;

  filters: {
    "DecryptionKeyUpdated(bytes32,bytes32)": TypedContractEvent<
      DecryptionKeyUpdatedEvent.InputTuple,
      DecryptionKeyUpdatedEvent.OutputTuple,
      DecryptionKeyUpdatedEvent.OutputObject
    >;
    DecryptionKeyUpdated: TypedContractEvent<
      DecryptionKeyUpdatedEvent.InputTuple,
      DecryptionKeyUpdatedEvent.OutputTuple,
      DecryptionKeyUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenUpdated(address,address)": TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;
    TokenUpdated: TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;

    "TokensDistributed(address,uint256,bytes32,address)": TypedContractEvent<
      TokensDistributedEvent.InputTuple,
      TokensDistributedEvent.OutputTuple,
      TokensDistributedEvent.OutputObject
    >;
    TokensDistributed: TypedContractEvent<
      TokensDistributedEvent.InputTuple,
      TokensDistributedEvent.OutputTuple,
      TokensDistributedEvent.OutputObject
    >;
  };
}
