export const BaseType = {
    text: "String",
    textarea: "String",
    number: "Number",
    select: "String",
    multiselect: "String[]",
    boolean: "Boolean",
    date: "Date",
    time: "Time",
    tags: "String[]",
    image: "Image",
    profile: "Profile",
    video: "Video",
    file: "File",
    richtext: "RichText",
    percent: "Number",
    barcode: "String",
    checkbox: "Boolean",
    cascader: "String",
    relation_one: "Relation(one)",
    relation_many: "Relation(many)",
    experience: "Experience[]",
    progress: "Number|Items",
    datetime: "Datetime",
    daterange: "DateRange",
    multidate: "Date[]",
    meta_items: "Items[]",
    multiimage: "Image[]",
    multivideo: "Video[]",
    identity_verification: "String",
    other_verification: "String",
}

export const preSetsType = {
    user_select: "user_select",
    city: "city",
    country: "country",
    phone: "phone",
    email: "email",
    url: "url",
    map: "map",
    currency: "currency",
    rating: "rating",
    percent: "percent",
    progress: "progress",
    constellation: "constellation",
    skills: "skills",
    work_experience: "work_experience",
    education_experience: "education_experience",
    certificate_experience: "certificate_experience",
    custom_experience: "custom_experience",
    identity_verification: "identity_verification",
    other_verification: "other_verification",
    barcode: "barcode",
    cascader: "cascader",
    relation: "relation",
}

// export const preSetsType = [
//     { key: "user_select", label: "选择用户", desc: "关联至用户列表", baseType: "relation_one" },
//     { key: "city", label: "城市（省/市/区）", desc: "支持是否显示区县", baseType: "text" },
//     { key: "country", label: "国家/地区", desc: "全球国家选择", baseType: "select" },
//     { key: "phone", label: "手机", desc: "格式校验", baseType: "text" },
//     { key: "email", label: "邮箱", desc: "格式校验", baseType: "text" },
//     { key: "url", label: "URL 链接", desc: "格式校验", baseType: "text" },
//     { key: "map", label: "地图位置", desc: "坐标/手动输入", baseType: "text" },
//     { key: "currency", label: "货币金额", desc: "币种选择", baseType: "number" },
//     { key: "rating", label: "评分（星级）", desc: "最大星数", baseType: "number" },
//     { key: "percent", label: "百分比", desc: "0-100", baseType: "percent" },
//     { key: "progress", label: "进度", desc: "进度条显示", baseType: "number" },
//     { key: "constellation", label: "星座", desc: "12星座选择", baseType: "select" },
//     { key: "skills", label: "技能", desc: "多技能选择", baseType: "multiselect" },
//     { key: "work_experience", label: "工作经历", desc: "职位、公司、时间等", baseType: "experience" },
//     { key: "education_experience", label: "教育经历", desc: "学校、专业、学历等", baseType: "experience" },
//     { key: "certificate_experience", label: "证书资质", desc: "证书、颁发机构等", baseType: "experience" },
//     { key: "custom_experience", label: "其他经历", desc: "自定义经历名称和事件", baseType: "experience" },
//     { key: "identity_verification", label: "实名认证", desc: "姓名、身份证号、身份证照片", baseType: "text" },
//     { key: "other_verification", label: "其他认证", desc: "自定义认证内容，支持文字和图片", baseType: "text" },
//     { key: "barcode", label: "条码", desc: "二维码、条形码等", baseType: "text" },
//     { key: "cascader", label: "级联选项", desc: "多级分类选择", baseType: "cascader" },
//     { key: "relation", label: "关联", desc: "关联其他表的数据", baseType: "relation_one" },
// ]